name: CITEST

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'CI'
      cool:
        description: 'Coolness'
        required: true
        default: 'no'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.build_type }}"
          echo "Tags: ${{ github.event.inputs.cool }}"